name: Create release

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1.2
          use-public-rspm: true

      - name: Download dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools

      - name: Zip the Lua files
        # We want the top-level directory to be "acronymsdown",
        # instead of "inst". So we first copy the files to a new directory.
        run: |
          mkdir -p /tmp/acronymsdown
          cp ./inst/*.lua /tmp/acronymsdown
          cd /tmp
          zip -r acronymsdown.zip acronymsdown/

      - name: Create R Package
        run: make doc build

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          files: |
            ./acronysmdown_*.tar.gz
            /tmp/acronymsdown.zip
