name: Automatic testing

on:
  push:
    # Run on all branches, except gh-pages (as it is only for documentation)
    branches-ignore: [gh-pages]
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      # We want to test all combinations of the matrix
      fail-fast: false
      matrix:
        R: [ '4.1.2' ]
        # In RStudio 1.5.114, the bundled pandoc is 2.11.4
        pandoc: [ '2.11.4', '2.16.2', '2.17.0.1' ]
    name: Testing R ${{ matrix.R }} - Pandoc ${{ matrix.pandoc }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:

      - name: Checkout the source code
        uses: actions/checkout@v2

      - name: Setup pandoc ${{ matrix.pandoc }}
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: ${{ matrix.pandoc }}

      - name: Setup R ${{ matrix.R }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
          use-public-rspm: true

      - name: Download dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: testthat, devtools

      - name: Build and install package
        run: make doc build install

      - name: Run automatic tests
        run: make tests

      - name: Run R CMD CHECK
        run: make check
